// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmhniutoisfrewynrmun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtaG5pdXRvaXNmcmV3eW5ybXVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMjU5MjEsImV4cCI6MjA2NDcwMTkyMX0.Ff2ej-xSv-ov23HUYmYxcvaXdVyAYHMSR24WOGPYfG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);